name: lolisnatcher
description: Booru Client with the ability to batch download Images.
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.3.1+180

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  alice: ^0.3.2
  app_links: ^3.4.1
  auto_size_text: ^3.0.0
  awesome_notifications: ^0.7.4+1
  chewie: ^1.3.6
  crypto: ^3.0.2
  cupertino_icons: ^1.0.5
  # dart_vlc: ^0.3.0
  dart_vlc:
    git:
      # 0.3.0 - synced with original github repo, they now use higher version of vlclib
      url: "https://github.com/NANI-SORE/dart_vlc.git"
      ref: 5fbe5c8fb2dd9991ccc440347e51110001aa9435
  dio: ^4.0.5
  dropdown_search: ^5.0.5
  fast_marquee:
    git:
      # url: "https://github.com/hacker1024/fast_marquee.git" # original
      url: "https://github.com/NANI-SORE/fast_marquee.git"
      ref: 828e79014ed5fd73062d6a24db14b6c114ac175b # master - forked to add richtext
  flash: ^2.0.5
  flex_color_picker: ^3.0.0
  flutter_displaymode: ^0.5.0
  flutter_improved_scrolling: ^0.0.3
  flutter_inappwebview: ^5.7.2+3
  flutter_inner_drawer:
    git:
      url: "https://github.com/NANI-SORE/flutter_inner_drawer.git"
      ref: 8e50920055dcb04b6b58560629daced7b86be36e # master
  flutter_linkify: ^5.0.2
  font_awesome_flutter: ^10.3.0
  get: ^4.6.5
  google_fonts: ^3.0.1
  html: ^0.15.1
  huge_listview: ^2.0.4
  image: ^4.0.5
  intl: ^0.17.0
  keyboard_actions: ^4.1.0
  logger_fork: ^1.2.0
  logger_flutter_fork: ^1.3.1
  # local_auth: ^2.1.0
  # marquee: ^2.2.2 # replaced with fast_marquee
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  photo_view: # ^0.12.0
    git:
      url: "https://github.com/NANI-SORE/photo_view.git"
      ref: e1efd408a788d497ef76a6ab755c648cc93e9380 # master
  preload_page_view: ^0.1.6
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.5
  sqflite_common_ffi: ^2.2.0+1
  sqflite: ^2.2.2
  statsfl: ^2.3.0
  transparent_image: ^2.0.0
  uuid: ^3.0.7
  vibration: ^1.7.5
  video_player: ^2.4.10
  waterfall_flow: ^3.0.2
  xml: ^6.1.0



flutter_icons:
  android: true
  image_path: "assets/images/iconFG.png"
  adaptive_icon_background: "assets/images/iconBG.png"
  adaptive_icon_foreground: "assets/images/iconFG.png"



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

dependency_overrides:
  ffi: ^2.0.1 # to override dart_vlc to use newer ffi to allow installing alice
  sensors_plus: ^2.0.1 # to override logger_flutter_fork to use newer sensors_plus to allow installing alice



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/drawer_icon.png
    - assets/images/loading.gif

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
