name: LoliSnatcher
description: Booru Client with the ability to batch download Images.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.8.6+161

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  http: ^0.13.4
  dio: ^4.0.0
  xml: ^5.3.1
  intl: ^0.17.0
  uuid: ^3.0.5
  path_provider: ^2.0.5
  flex_color_picker: ^2.1.2
  flutter_launcher_icons: ^0.9.2
  flash: ^2.0.3
  dropdown_search: ^1.0.4
  marquee: ^2.2.0
  auto_size_text: ^3.0.0-nullsafety.0
  statsfl: ^2.0.1+1
  vibration: ^1.7.4-nullsafety.0
  get: ^4.3.8
  permission_handler: ^8.1.6 # next update will require android sdk version 31
  image: ^3.0.8
  google_fonts: ^2.1.0
  photo_view: # ^0.12.0
    git:
      url: "https://github.com/NANI-SORE/photo_view.git"
  html: ^0.15.0
  flutter_staggered_grid_view: # ^0.4.0
    git:
      url: "https://github.com/bladeofgod/flutter_staggered_grid_view.git"
  waterfall_flow: ^3.0.1
  scroll_to_index: ^2.1.0
  transparent_image: ^2.0.0
  video_player: ^2.2.5
  dart_vlc: ^0.1.8
  chewie: ^1.2.2
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.1.0
  preload_page_view: ^0.1.6
  flutter_displaymode: ^0.3.2
  crypto: ^3.0.1
  keyboard_actions: ^3.4.4
  flutter_improved_scrolling: ^0.0.3

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/iconFG.png"
  adaptive_icon_background: "assets/images/iconBG.png"
  adaptive_icon_foreground: "assets/images/iconFG.png"




dev_dependencies:



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/drawer_icon.png
    - assets/images/loading.gif

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
